version: '3.8'

services:
  webapp:
    build: .
    container_name: webapp_container
    ports:
      - "5000:5000"
    command: python app.py
    env_file:
      - .env
    environment:
      TZ: Europe/Kiev
      DATABASE_URL: sqlite:////app/database.db
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672//
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
    volumes:
      - ./:/app
    depends_on:
      - rabbitmq


  celery_worker:
    build: .
    container_name: celery_worker_container
    command: celery -A email_worker worker --loglevel=info
    env_file:
      - .env
    environment:
      TZ: Europe/Kiev
      DATABASE_URL: sqlite:////app/database.db
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672//
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
    volumes:
      - ./:/app
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq_container
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEPRECATED_FEATURES_PERMIT_GLOBAL_QOS: "true"
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest


  celery_beat:
    build: .
    container_name: celery_beat_container
    command: celery -A email_worker beat --loglevel=info
    env_file:
      - .env
    environment:
      TZ: Europe/Kiev
      DATABASE_URL: sqlite:////app/database.db
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672//
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
    volumes:
      - ./:/app
    depends_on:
      - rabbitmq